name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  asan_ubsan:
    name: ASan + UBSan
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DENABLE_BENCHMARKS=OFF -DENABLE_ASAN_UBSAN=ON
          make -j$(nproc)
      - name: Run unit tests
        run: ./build/tests/all_tests

  msan:
    name: MSan
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DENABLE_BENCHMARKS=OFF -DENABLE_MSAN=ON
          make -j$(nproc)
      - name: Run unit tests
        run: ./build/tests/all_tests

  tsan:
    name: TSan
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Fix TSan memory mapping
        run: sudo sysctl vm.mmap_rnd_bits=28
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DENABLE_BENCHMARKS=OFF -DENABLE_TSAN=ON
          make -j$(nproc)
      - name: Run unit tests
        run: ./build/tests/all_tests
